Why my projects cannot support NetBSD (yet)
===========================================
Shlomi Fish <shlomif@cpan.org>
:Date: 2019-15-09
:Revision: $Id$

[id="summary"]
TL;DR Summary
-------------

My public-facing projects (open source ones/etc) cannot support https://www.netbsd.org/[NetBSD] yet, despite being capable of being built and tested on many Linux distributions, FreeBSD, and often also Microsoft Windows, due to the lack of version 5 of DocBook/XML in http://www.pkgsrc.org/[pkgsrc].

[id="intro"]
Introduction
------------

This is a sequel to a previous https://github.com/shlomif/what-i-learned-from-porting-to-freebsd[feature] about what I learned from porting my projects to build and pass tests FreeBSD and which received some coverage on reddit and hackernews. In a hackernews comment, someone suggested that "`now you should try openbsd or netbsd, as they are even less tolerant of linux-isms`". As this comment seemed to be of merit, I decided to try porting them to NetBSD which I heard was easier to install at the time than OpenBSD (which may no longer be true).

Note that I don't expect this sequel to be as popular as the original, and I'm not writing it for achieving worldwide fame and fortune, just as an update on my progress.

[id="what_worked"]
What worked
-----------

NetBSD was fairly easy to install for me on a VirtualBox VM, as easy as FreeBSD and much easier than the https://shlomif-tech.livejournal.com/64318.html[user-hostile installer of Arch linux] (which to its defence was replaced by an easy to use graphical installer in https://manjaro.org/[Manjaro] and possibly some other Arch derivatives). Setting up pkgsrc was fairly straightforward as well (but could have been made somewhat easier by adding some preinstalled scripts). NetBSD seemed fast enough or even very fast, and it was easy to build many of my projects dependencies.

Note that I used a graphical web browser on the host mageia linux system, to look up some commands and idioms out of convenience, but everything may be documented inside the guest VM's bundled documentation - I didn't check.

[id="the_obstacle"]
The Obstacle:
-------------

I was unable to proceed because I discovered that https://en.wikipedia.org/wiki/DocBook[DocBook/XML] was still stuck at version 4.5 in pkgsrc (see http://pkgsrc.se/textproc/docbook-xml ) despite the fact that DocBook 5.0 https://docbook.org/schemas/5x.html[was released in 2008] (over 10 years ago) and that it was already available in FreeBSD and many Linux distributions, including some that are likely even less popular than NetBSD (including https://www.mageia.org/en/[Mageia] which I happen to use on some systems and which I contribute to).

Since I lack the knowledge and interest to prepare a DocBook/XML 5.x port for pkgsrc/NetBSD and it seemed like general negligence or apathy towards it, and pojects that make use of it, I decided that I won't officially support building my projects there. It may work or it may not, but you'll need to install DocBook 5.x or contribute a package to pkgsrc yourself. Patches and pull requests that improve portability to NetBSD, OpenBSD, or other non-EOLed Unix-like OSes or non-EOLed MS Windows versions, will be welcome and reviewed and hopefully merged. You can still ask me for help, but I may say that I do not support pkgsrc-based OSes and ask you to either use a different OS (possibly inside a VM), give up, or do the work yourself.

I believe that supporting DocBook/XML 5.0 is important enough for many other FOSS projects that use it, that upgrading to it should be a priority for pkgsrc, and I am surprised that it fell between the chairs for so long. I was told that FreeBSD has more manpower than NetBSD, although it may have other organisational issues - a fact which may explain the issue.

[id="bsd_blame"]
Addendum: why the BSDs should not blame the USL vs BSDi lawsuits for Linux's dominance
--------------------------------------------------------------------------------------

It is always easier to blame your problems on someone else, the world at large or a past event.
It is also usually wrong because only you can fix your problem, and the problem may be at you.

Here are some examples: from my impression most Israeli Jews blame the Lebanese, the Hizbullah,
Syria and/or Iran with whatever violent acts happen in the Israel-Lebanon border. I, on the other hand,
despite being an Israeli citizen, an ethnic (but secular) Jew, and an Israeli resident, who likes
living in Israel, and does not support the complete abolishment of the State of Israel — blames
Israel for all that. It's not that I think the our enemies are good and benevolent, it's just that
I think Israel is doing many things wrong, and must not shift the blame for its own problems.

When I wrote about it in https://shlomif.livejournal.com/10530.html[my blog] I received two
"you are wrong" comments from two Israeli Jews, and a Jewish coworker of mine scolded me
for my spite, after greeting other good morning in the workplace. Now I also think Israel should also adopt
http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin's long under-recognised approach]
to justice, peace, and good will through forgiveness, nobility, trust and chivalry which
helped him convert the Knights Templar from batshit crazy "religious" and violent zealots
(who were much less sane than even the most zealous 21st century Muslim activist) into
people who were rational, non-violent, mostly sane, and refused to fight his forces even
under the orders of their religious leaders. (And naturally, he didn't actively harm the
innocent civilians who had previously suffered from the Knights reign of terror.
I believe a modern take on this approach, will work with Hizbullah militants as well,
but our bylaws necessitate "punishing" the offenders by jail time.

Anyway, I later talked with a man who resided in Lebanon on https://en.wikipedia.org/wiki/Freenode[Freenode]
and despite whatever hardships he may have suffered from Israeli air raids (hard to know how much because
media coverage is skewed) told me that he thinks Lebanon is to blame. I later pointed him to my
https://www.shlomifish.org/[home site] where I published some essays and stories on this issue (and
many others) and he later emailed me saying that he agreed with my opinions.

When I told all that to a different Israeli jewish and secular friend in a different Internet chat,
he told me and the other participants that making peace would be easy if the two of us were the
leaders of Israel and Lebanon.

'''

Here is another example: many people have placed the blame on the poor economic
performance of some former British empire colonies on the former British occupiers.
But as https://www.youtube.com/watch?v=p-fRo5-p9hE[Monty Python brilliantly and
amusingly pointed in their sketch "What have the Romans done to us"], they were
not quite so bad, and the blame was on the former colonies' governments mismanagement.
And for Monty Python's defence, while that sketch appears to be pro-Roman
and anti-Judean, they have many other scenes in https://en.wikipedia.org/wiki/Monty_Python%27s_Life_of_Brian[the film] portraying the Romans
as stupid and incompetent. Monty Python never took any prisoners.

'''

So what does it have to do with BSD? OK, so the
https://en.wikipedia.org/wiki/UNIX_System_Laboratories,_Inc._v._Berkeley_Software_Design,_Inc.[USL vs. BSDI] and it was
ugly, threw 386BSD and its forks into some confusion and uncertainity, and may have caused some loss of time and man power, but
do you really think this is the only reason that Linux and GNU are nowadays more popular than the possibly superior FreeBSD,
NetBSD and OpenBSD?

The trial was over by 1994, and I recall being instructed to use FreeBSD instead of Linux on a
Pentium I "workstation" desktop box in 1996 back when I worked for https://www.shlomifish.org/prog-evolution/shlomif-at-cortext.html[Cortext web design]
because they told me it was much more mature and better, and were probably right. Paul Graham http://paulgraham.com/javacover.html[thought] that
FreeBSD and not Linux would diminish Sun's server market as late as 2001, when I already used Red Hat Linux or Mandrake Linux as a desktop
OS and was happy with my choice.

But now the Linux kernel and its GNU / etc. runtime are now much more popular than the BSDs despite
whatever technical drawbacks they may have, not because of the USL vs BSDI court case, but because
of superior (or possibly less inferior) management by the forces who developed and supported them.

The BSDs should take responsibility for their own problems rather than blame it on a distant past event
that had limited influence back then and had very little influence since.

Guess what? I think it may not be too late. If say FreeBSD is happy being a niche OS, then they can
remain that now. If they want to become more popular than Linux (and possibly overtake both Windows
and macOS on the desktop - why think small?) they should https://www.joelonsoftware.com/2000/06/03/strategy-letter-iii-let-me-go-back/[admit it]
and try to see what Linux/etc. is doing better, and how they could catch up and improve upon it. I
have many theories about what the BSDs may be doing wrong, but they are out of the scope here, and
others may have different suggestions and may disagree with me.

But to https://en.wikipedia.org/wiki/The_Fault_in_Our_Stars[quote Shakespeare] "`The fault, Dear Brutus,
is not in our stars`".
